name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Compress and save Docker image as tarball
        run: |
          echo "before compress"
          ls -alh
          tar -czvf examples.tar.gz examples
          echo "after compress"
          ls -alh
      - name: Upload compressed tarball via SCP
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass rsync
          mkdir -p ~/.ssh
          # Add remote server's public key to known_hosts
          ssh-keyscan ${{ secrets.PRODUCTION_SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Upload file via SCP
        run: |
          sshpass -p ${{ secrets.PRODUCTION_SERVER_PASSWORD }} ssh ${{ secrets.PRODUCTION_SERVER_USER }}@${{ secrets.PRODUCTION_SERVER_HOST }} "mkdir -p /www/wwwroot/examples/my-bun/"
          # 然后上传文件
          sshpass -p ${{ secrets.PRODUCTION_SERVER_PASSWORD }} rsync -avz -e ssh examples.tar.gz ${{ secrets.PRODUCTION_SERVER_USER }}@${{ secrets.PRODUCTION_SERVER_HOST }}:/www/wwwroot/examples/
      - name: SSH into the server and run commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_SERVER_HOST }}
          username: ${{ secrets.PRODUCTION_SERVER_USER }}
          password: ${{ secrets.PRODUCTION_SERVER_PASSWORD }}
          port: 22
          script: |
            tar -xzvf /www/wwwroot/examples/examples.tar.gz -C /www/wwwroot/examples/ --strip-components=1
            rm -f /www/wwwroot/examples/examples.tar.gz
